### ISSUE TITLE
Adding Custom Icons and Custom Sound in the .aar file induces a bug

### ISSUE THREAD

**Issue by Beno7** [hippogamesunity/SimpleAndroidNotificationsPublic#56]
Hi,

Our app crashes upon integration with SimpleAndroidNotifications Paid / Premium version with the following error logs:

`AndroidJavaException: java.lang.ClassNotFoundException: com.hippogames.simpleandroidnotifications.Controller java.lang.ClassNotFoundException: com.hippogames.simpleandroidnotifications.Controller
                                              at java.lang.Class.classForName(Native Method)
                                              at java.lang.Class.forName(Class.java:453)
                                              at java.lang.Class.forName(Class.java:378)
                                              at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                              at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
                                              at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
                                              at android.os.MessageQueue.next(MessageQueue.java:395)
                                              at android.os.Looper.loop(Looper.java:181)
                                              at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.hippogames.simpleandroidnotifications.Controller" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file ...`

Upon repeated tries, I have noticed that the error occurs when I use the altered .aar file (with additional custom sounds and custom icons). The said file was altered via the following steps (mentioned in the manual):

**For Custom Icons**
1. find plugin .aar file
2. change extension from .aar to .zip(you can also open .aar directly if your file manager supports
  this feature)
3. open .zip in any archive program
4. find /res folder
5. provide all icon sizes and put files to each /drawable folder
6. change extension from .zip to .aar
7. extend enum NotificationIcon
8. update string GetSmallIconName(NotificationIcon icon) if needed
 
**For Custom Sound**
1. find .aar archive at Assets\SimpleAndroidNotifications\Plugins\Android\simple-android- notifications.aar
2. change extension from .aar to .zip (you can also open .aar directly if your file manager supports this feature)
3. open .zip in any archive program
4. find /res folder
5. create /raw folder inside /res folder
6. place your sound files here. Tested extensions: mp3, wav. Sound file name must contain only [a-
z0-9_.]. Don’t use uppercase! You must get something like simple-android-
notifications.aar/res/raw/ding.mp3.
7. change extension from .zip back to .aar
8. Set CustomSound parameter when creating a notification, use file name only (without
extension)

If it helps, we are using MacOS Mojave, and we re-import the .aar file via deleting the currently existing file in Unity, and drag-and-dropping the altered .aar file onto Unity. The app crashes somewhere at the beginning of the app's execution (it hinders the app from loading the first scene). Below is a link to our altered .aar file (compressed into a zip file).
[simple-android-notifications.aar.zip](https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/files/2928895/simple-android-notifications.aar.zip)

**Comment by hippogamesunity** [comment]
Hi! There should be noted in the manual that you should use Windows to work
with ZIP, as MacOs add hidden meta files and makes archive broken for
Android builds.

**Comment by hippogamesunity** [comment]
Yep, looks like MacOs breaks your aars.

**Comment by Beno7** [comment]
How dumb of me to miss that detail out. Did what you said, and it doesn't crash anymore. Cheers!

**Comment by hippogamesunity** [comment]
Great, hope to see your feedback on the Asset Store!
