### ISSUE TITLE
Invalid notification (no valid small icon)

### ISSUE THREAD

**Issue by ghost** [hippogamesunity/SimpleAndroidNotificationsPublic#78]
paid version. unity 2019.3.10f1. after compile, when notification is triggered.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.supershot.knife, PID: 1094
    java.lang.RuntimeException: Unable to start receiver com.hippogames.simpleandroidnotifications.Controller: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=Default pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x10 color=0xff008000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4038)
        at android.app.ActivityThread.access$1500(ActivityThread.java:269)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2021)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7857)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=Default pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x10 color=0xff008000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:537)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:516)
        at android.app.NotificationManager.notify(NotificationManager.java:449)
        at android.app.NotificationManager.notify(NotificationManager.java:425)
        at com.hippogames.simpleandroidnotifications.Controller.onReceive(Controller.java:170)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4029)
        at android.app.ActivityThread.access$1500(ActivityThread.java:269) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2021) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7857) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by ghost** [comment]
var notificationParams2 = new NotificationParams
            {
                Id = UnityEngine.Random.Range(0, int.MaxValue),
                Delay = TimeSpan.FromSeconds(2 ),
                Title = "Welcome onboard Super Knifer! ",
                Message = "Our team is happy to meet you,\n feel free to ask anythink.",
                Ticker = "Our team is happy to meet you,\n feel free to ask anythink.",
                Sound = true,
                Multiline = true,
                Vibrate = true,
                Vibration = new[] { 500, 500, 500, 500, 500, 500 },
                Light = true,
                LightOnMs = 1000,
                LightOffMs = 1000,
                LightColor = Color.red,
                SmallIcon = NotificationIcon.superknifeshot,
                SmallIconColor = new Color(0f, 0.5f, 0f),
                LargeIcon = "app_icon",
                ExecuteMode = NotificationExecuteMode.Inexact,
                Importance = NotificationImportance.Max
                //CallbackData = "2"
            };

            NotificationManager.SendCustom(notificationParams2);

**Comment by hippogamesunity** [comment]
Hi! Does this happen with empty empty project?

пн, 4 мая 2020 г., 21:12 guycorpgames <notifications@github.com>:

**Comment by ghost** [comment]
Hi, yes, same problem. new project from scratch.

**Comment by hippogamesunity** [comment]
I'll check this soon, thanks.

**Comment by ghost** [comment]
just tested with re downloaded asset from store, it works. 
with custom logo I still have the error, i'll try again to make the .aar file with custom logo included

**Comment by ghost** [comment]
Hi,

it works with default icons, but not with custom icon. with same aar.

---
Nicolas GUY, founder
+33.666.294.561

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hippogamesunity** [comment]
On some UI shells notification icons may be displayed in different ways. You can try another devices.
